version: '3.9'

networks:
    webapi:

services:
    #Nginx Service
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: ${APP_NAME}-nginx
        ports:
            - '${APP_PORT}:80'
        links:
            - php
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
        networks:
            - webapi

    #PHP Service
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: ${APP_NAME}-php
        volumes:
            - ./:/var/www/html
        ports:
            - '${APP_PHP_PORT}:4000'
        networks:
            - webapi

    #MySQL Database Service
#    mysql:
#        image: 'mysql:8.0'
#        container_name: ${APP_NAME}-mysql
#        restart: unless-stopped
#        tty: true
#        volumes:
#            - ./docker/mysql:/var/lib/mysql
#        ports:
#            - "${DB_PORT}:3306"
#        environment:
#            MYSQL_ROOT_USER: ${ROOT_USER}
#            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
#            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#            SERVICE_NAME: mysql
#        networks:
#            - webapi

    #MySQL Web Administration Services
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: ${APP_NAME}-phpmyadmin
#        restart: always
#        ports:
#          - "${PMA_PORT}:80"
#        depends_on:
#            - mysql
#        environment:
#            PMA_HOST: mysql
#        volumes:
#          - ./docker/phpmyadmin:/var/lib/mysql
#        networks:
#            - webapi
